version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.prod
    container_name: backend
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - Backend/.env
    networks:
      - app-network
    restart: unless-stopped
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_ROOT_URL=http://YOUR_SERVER_IP:8000
    ports:
      - "0.0.0.0:4005:4005"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
