services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.prod
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - Backend/.env
    depends_on:
      - minio
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    ports:
      - "4001:4001"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  minio-data:
