services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - Backend/.env
    volumes:
      - ./Backend:/app
    networks:
      - app-network
    depends_on:
      - frontend
    # Add DNS resolvers to fix MongoDB SRV resolution issues
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1'
    container_name: frontend
    ports:
      - "4006:4006"
    volumes:
      - ./Frontend:/app   
      - /app/node_modules    
      - /app/.next            
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      - FAST_REFRESH=true
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=4005
      # Turbopack specific settings  
      - RUST_LOG=turbopack=debug
      - NEXT_TELEMETRY_DISABLED=1
      - FORCE_COLOR=1
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
