services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - Backend/.env
    volumes:
      - ./Backend:/app
    networks:
      - app-network
    depends_on:
      - frontend
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1'
    container_name: frontend
    ports:
      - "4001:4001"
    volumes:
      - ./Frontend:/app       # 挂载源代码
      - /app/node_modules     # 防止覆盖容器内的 node_modules
      - /app/.next            # 防止覆盖 Next.js 缓存
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
